In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [2]:
import numpy as np

ratings = np.array(
    [
        [3.0, 3.0, 2.0, 3.0, 3.0, 3.0],
        [4.0, 1.0, 1.0, 4.0, 5.0, 3.0],
        [1.0, 2.0, 2.0, 1.0, 1.0, 2.0],
        [3.0, 2.0, 1.0, 3.0, 4.0, 3.0],
        [1.0, 5.0, 3.0, 1.0, 1.0, 3.0],
        [2.0, 5.0, 3.0, 2.0, 3.0, 4.0],
        [2.0, 2.0, 1.0, 2.0, 2.0, 2.0],
        [1.0, 4.0, 3.0, 1.0, 2.0, 3.0],
    ]
)

<IPython.core.display.Javascript object>

In [3]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

K = 2
R = ratings

N = len(ratings)
M = len(ratings[0])
P = np.random.rand(N, K)
Q = np.random.rand(M, K)
ratings = tf.placeholder(tf.float32, name="ratings")
P_matrix = tf.Variable(P, dtype=tf.float32)
Q_matrix = tf.Variable(Q, dtype=tf.float32)
P_times_Q = tf.matmul(P_matrix, Q_matrix, transpose_b=True)
squared_error = tf.square(P_times_Q - ratings)
loss = tf.reduce_sum(squared_error)

Instructions for updating:
non-resource variables are not supported in the long term


<IPython.core.display.Javascript object>

In [4]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

<IPython.core.display.Javascript object>

In [5]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(5000):
    sess.run(train, {ratings: R})

final_P_times_Q = np.around(sess.run(P_times_Q), 3)
print(final_P_times_Q)
print()
final_P_matrix = np.around(sess.run(P_matrix), 3)
print(final_P_matrix)
print()
final_Q_matrix = np.transpose(np.around(sess.run(Q_matrix), 3))
print(final_Q_matrix)
print()

[[2.721 2.93  1.932 2.721 3.375 3.185]
 [4.056 1.135 0.787 4.056 4.902 3.014]
 [0.93  2.376 1.55  0.93  1.208 1.826]
 [3.136 1.898 1.269 3.136 3.83  2.877]
 [0.846 4.844 3.146 0.846 1.206 3.099]
 [2.157 4.917 3.211 2.157 2.778 3.916]
 [1.826 1.825 1.205 1.826 2.258 2.061]
 [1.226 4.198 2.733 1.226 1.635 2.979]]

[[1.422 0.955]
 [2.364 0.085]
 [0.382 0.895]
 [1.75  0.488]
 [0.146 1.924]
 [0.931 1.83 ]
 [0.965 0.582]
 [0.424 1.621]]

[[1.705 0.39  0.275 1.705 2.057 1.22 ]
 [0.311 2.488 1.615 0.311 0.471 1.519]]



<IPython.core.display.Javascript object>

In [7]:
new_user_indices = [1, 2, 4, 5]
new_user_ratings = [2, 2, 1, 2]
new_user_P_row_initial = np.random.rand(1, K)
new_user_P_row = tf.Variable(new_user_P_row_initial, dtype=tf.float32)
new_user_P_row_times_Q = tf.matmul(new_user_P_row, final_Q_matrix)
res = tf.gather(new_user_P_row_times_Q, new_user_indices, axis=1)
squared_error = tf.square(new_user_ratings - res)
loss = tf.reduce_sum(squared_error)
optimizer = tf.train.GradientDescentOptimizer(0.01)
predict = optimizer.minimize(loss)

<IPython.core.display.Javascript object>

In [8]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(50000):
    sess.run(predict)

<IPython.core.display.Javascript object>

In [9]:
final_new_user_P_row_times_Q = np.around(sess.run(new_user_P_row_times_Q), 3)
print(np.round(final_new_user_P_row_times_Q))

[[1. 2. 2. 1. 1. 2.]]


<IPython.core.display.Javascript object>